export const apiEndpoints = {
  adminLogin: '/v1/admin/login',
  uploadsDocument: '/v1/globals/docUplaods',
  getAllproperty: '/v1/property/getAllproperty',
  addPropertyDetails: '/v1/property/addPropertyDetails',
  deleteProperty: '/v1/property/deleteProperty',
  getPropertyById: '/v1/property/getPropertyById',
  updatePropertyDetails: '/v1/property/updatePropertyDetails',
  addFloorPlanAndPricing: '/v1/property/addFloorPlanAndPricing',
  updateBrokerageDetails: '/v1/property/updateBrokerageDetails',
  getAllBuilder: '/v1/builder/getAllBuilder',
  getBuilderById: '/v1/builder/getBuilderById',
  addPropertyCategory: '/v1/propertyCategory/addPropertyCategory',
  addPropertySubCategory: '/v1/propertysubCategory/addPropertySubCategory',
  getAllPropertyCategory: '/v1/propertyCategory/getAllPropertyCategory',
  updatePropertyCategory: '/v1/propertyCategory/updatePropertyCategory',
  deletePropertyCategory: '/v1/propertyCategory/deletePropertyCategory',
  getAllpropertySubCategory:
    '/v1/propertySubCategory/getAllpropertySubCategory',
  getPropertyCategoryById: '/v1/propertyCategory/getPropertyCategoryById',
  getAllAmenities: '/v1/amenities/getAllAmenities',
  addAmenities: '/v1/amenities/addAmenities',
  getAmenitiesById: '/v1/amenities/getAmenitiesById',
  updateAmenities: '/v1/amenities/updateAmenities',
  deleteAmenities: '/v1/amenities/deleteAmenities',
  getAllLocationAdvantage: '/v1/locationAdvantage/getAllLocationAdvantage',
  addLocationAdvantage: '/v1/locationAdvantage/addLocationAdvantage',
  getLocationAdvantageById: '/v1/locationAdvantage/getLocationAdvantageById',
  updateLocationAdvantage: '/v1/locationAdvantage/updateLocationAdvantage',
  deleteLocationAdvantage: '/v1/locationAdvantage/deleteLocationAdvantage',
  getAllBank: '/v1/bank/getAllBank',
  addBank: 'v1/bank/addBank',
  updateBank: '/v1/bank/updateBank',
  deleteBank: '/v1/bank/deleteBank',
  getBankById: '/v1/bank/getBankById',
  getAllNearByArea: '/v1/nearByArea/getAllNearByArea',
  addNearByArea: '/v1/nearByArea/addNearByArea',
  updateNearByArea: '/v1/nearByArea/updateNearByArea',
  deleteNearByArea: '/v1/nearByArea/deleteNearByArea',
  getNearByAreaById: '/v1/nearByArea/getNearByAreaById',
  getAllFurnishingDetail: '/v1/furnishingDetail/getAllFurnishingDetail',
  addFurnishingDetail: '/v1/furnishingDetail/addFurnishingDetail',
  updateFurnishingDetail: '/v1/furnishingDetail/updateFurnishingDetail',
  deleteFurnishingDetail: '/v1/furnishingDetail/deleteFurnishingDetail',
  getFurnishingDetailById: '/v1/furnishingDetail/getFurnishingDetailById',
  getAllSpecification: '/v1/specification/getAllSpecification',
  addSpecification: '/v1/specification/addSpecification',
  updateSpecification: '/v1/specification/updateSpecification',
  deleteSpecification: '/v1/specification/deleteSpecification',
  getSpecificationById: '/v1/specification/getSpecificationById',
  addSubCompany: '/v1/subCompany/addsubcompany',
  getAllSubCompanies: '/v1/subCompany/getallsubcompany',
  addSubscription: '/v1/subscription/addSubscription',

  // builder
  addBuilder: '/v1/builder/addBuilder',
  getbuilderPastProperty: '/v1/builderPastProperty/getbuilderPastProperty',
  addbuilderPastProperty: '/v1/builderPastProperty/addbuilderPastProperty',
  updatebuilderPastProperty:
    '/v1/builderPastProperty/updatebuilderPastProperty',
  deletebuilderPastProperty:
    '/v1/builderPastProperty/deletebuilderPastProperty',
  getbuilderPastPropertyById:
    '/v1/builderPastProperty/getbuilderPastPropertyById',
  getAllBlogs: '/v1/blog/getAllBlog',
};
