export const apiEndpoints = {
  getAllBuilder: "/v1/builder/getAllBuilder",
  updateBuilder: "/v1/builder/updateBuilder",
  addBuilder: "/v1/builder/addBuilder",
  getAllproperty: "/v1/property/getAllproperty",
  getAllSubscription: "/v1/subscription/getAllSubscription",
  deleteSubscription: "/v1/subscription/deleteSubscription",
  updateSubscription: "/v1/subscription/updateSubscription",
  getSubscriptionById: "/v1/subscription/getSubscription",
  addSubscription: "/v1/subscription/addSubscription",
  getAllSubscriptionOrder: "/v1/subscriptionOrder/getAllSubscriptionOrder",
  getAllInvoice: "v1/invoice/getAllInvoice",
  getAllInvoiceForBuilder: "/v1/invoice/getAllInvoiceForBuilder?builderId=",
  getAllVisit: "/v1/visit/getAllVisit",
  getAllVisit2: "/v1/visit/getAllVisit?isPromoted=true",
  getAllEligibleClaims:
    "/v1/claim/getAllEligibleClaims?brokerId=640c30902cdf3673a29ae71d",
  getAllClaim: "/v1/claim/getAllClaim?claimType=all",
  getAllLoanQueryDetails:
    "/v1/loanQueryDetails/getAllLoanQueryDetails?brokerId=640c30902cdf3673a29ae71d",
  getAllRaiseQuery: "/v1/raiseQuery/getAllRaiseQuery?createdById=",
  getAllRaiseDispute:
    "/v1/raiseDispute/getAllRaiseDispute?builderId=641069056532f2569479fc9d&visitId=63ec81c4c5259bed7aa92f4f",
  getAllIntents: "/v1//builder/getAllIntents",
  addBlog: "/v1/blog/addBlog",
  getAllBlogs: "/v1/blog/getAllBlog",
  activeStatus: "/v1/blog/updateBlogStatus",
  getAllBlogsAdmin: "/v1/blog/getAllBlogAdmin",
  deleteBlog: "/v1/blog/deleteBlog",
  updateIntentStatus: "/v1/builder/updateIntentStatus",
  getAllContactus: "/v1/contactus/getAllContactus",
  uploadDOc: "v1/globals/docUplds",
  getAllRequestProperty: "/v1/requestProperty/getAllRequestProperty?builderId=",
};
